FROM hypriot/image-builder:latest

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    binfmt-support \
    qemu \
    qemu-user-static \
    xxd \
    live-boot \
    live-build \
    live-config \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN sed -i '1161s%umount%#umount%' /usr/share/debootstrap/functions

COPY builder/ /builder/

# build sd card image
CMD /builder/build.sh
